# Generated by Django 4.2.6 on 2023-10-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormantAnalyse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=40, null=True)),
                ("imgfile", models.FileField(blank=True, null=True, upload_to="")),
                ("content", models.TextField()),
            ],
        ),
    ]
