# Generated by Django 4.2.6 on 2023-10-26 07:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="C:\\projects\\mysite\\media"
                        ),
                        upload_to="",
                    ),
                ),
            ],
        ),
    ]
